version: 2

before:
  hooks:
    - ./scripts/internal/update-plugin-version.sh {{ .Tag }}

builds:
  - id: ralphex-windows
    main: ./cmd/ralphex
    binary: ralphex.windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{ trimsuffix (replace (replace .CommitDate "-" "") ":" "") "Z" }}

archives:
  - id: ralphex-windows
    ids:
      - ralphex-windows
    name_template: >-
      ralphex_windows_{{ .Version }}_{{ .Arch }}
    formats:
      - zip

release:
  prerelease: false
  make_latest: true
  name_template: "Windows {{ .Version }}"
